### PR TITLE
v0.2.2

### PR DESCRIPTION
**Pull request by crusaderky**
Now includes a C extension

### CODE REVIEW

**Comment by crusaderky** [comment]
Blocked by https://github.com/conda-forge/python-feedstock/issues/186

**Comment by isuruf** [comment]
@conda-forge-admin, please rerender

**Comment by crusaderky** [comment]
@isuruf the failure on Python 2.7 is expected - however I could not find anywhere in the documentation how to limit builts for python >= 3.5 only?
Also I cannot see a circleci build for Python 3.7 above - which is needed

**Comment by crusaderky** [comment]
I previously tried adding ``recipe/conda_build_config.yaml``:
```
python:
    - 3.5
    - 3.6
    - 3.7
```
but it seems to be ignored?

**Comment by isuruf** [comment]
See https://conda-forge.org/docs/meta.html#excluding-a-platform. `skip: true   # [py27]`

**Comment by isuruf** [comment]
We need to build all the dependencies for 3.7, which will happen soon. Until then 3.7 is not supported.

**Comment by isuruf** [comment]
You need to rerender when you skip python 2.7

@conda-forge-admin, please rerender

**Comment by crusaderky** [comment]
Thank you @isuruf for your help

**Pull request merged**
